# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 887b6e19578b563f8a1c33f4891be58e3916c1781e0c94cecd354b2240ffd4ef13e7fc3384bbe5772e130bc09d64ae6ae979a6d67186dab70a97fe6c534b91e1

test:
  secret_key_base: 65a71b544ed142c335d28ec38132ba16de3935757d758aab487e04990f8f5aaa6c377521ba7f5797e1d4f865a93eb2f5bf75af690b9ce1d82b7f72e9fe3f8f22

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
